"use client";
// Immutable character data
export const characters = [
  {
    id: 1,
    name: "Rachel",
    level: 26,
    className: "Ninja Archivist",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Reem_Reviews",
  },
  {
    id: 2,
    name: "Versteckt",
    level: 1,
    className: "Submarine Builder",
    faction: "Pond",
    location: "Exit of Hatenashi",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@0xVersteckt",
  },
  {
    id: 3,
    name: "Rolla",
    level: 1,
    className: "Demplar",
    faction: "Pond",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@rollablazer",
  },
  {
    id: 4,
    name: "Alex",
    level: 30,
    className: "Fairy Berserker",
    faction: "Demplar",
    location: "Luminous",
    profileUrl:
      "https://images.ctfassets.net/b474hutgbdbv/2V3dKNSD41QjeLowfolcG3/e9a4eb087190d640b9c6c982a17480d4/image.png",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Alexgill81",
  },
  {
    id: 5,
    name: "Inspired",
    level: 11,
    className: "El Shooter",
    faction: "Pork",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Inspired6910",
  },
  {
    id: 6,
    name: "CertifiedLoverBull",
    level: 16,
    className: "Korathax, Golden Titan",
    faction: "Demplar",
    location: "Labrynth",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Certified0x",
  },
  {
    id: 7,
    name: "Tommy",
    level: 17,
    className: "Flame Assassin",
    faction: "Demplar",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 8,
    name: "True Warrior",
    level: 10,
    className: "Crown of the Dying Suns",
    faction: "Demplar",
    location: "Labrynth",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@itstruewarrior",
  },
  {
    id: 9,
    name: "Denojah",
    level: 26,
    className: "Pip Captain",
    faction: "Pond",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@DenOJah",
  },
  {
    id: 10,
    name: "Sir Nemo",
    level: 31,
    className: "Demplar Samurai",
    faction: "Demplar",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@GhostHorama",
  },
  {
    id: 11,
    name: "MDK",
    level: 11,
    className: "Pond Enigma",
    faction: "Pond",
    location: "Labrynth",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@mdk0x",
  },
  {
    id: 12,
    name: "American Hearts",
    level: 9,
    className: "Phunk Knight",
    faction: "Pork",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@DragYourShadow",
  },
  {
    id: 13,
    name: "Chair",
    level: 14,
    className: "Phunk Knight",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@vrycmfy",
  },
  {
    id: 14,
    name: "Jest",
    level: 12,
    className: "Jester",
    faction: "Pork",
    location: "Watchtower",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Albertletour",
  },
  {
    id: 15,
    name: "Meggy",
    level: 17,
    className: "Counter Culture Martial Artist",
    faction: "Demplar",
    location: "Thieves Den",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@MeggyKr",
  },
  {
    id: 16,
    name: "Wicked",
    level: 10,
    className: "Jerks Adventurer",
    faction: "Demplar",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@WICKEDNESS4Eva",
  },
  {
    id: 17,
    name: "Ponderer",
    level: 11,
    className: "Steampunk",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@inthepondwater",
  },
  {
    id: 18,
    name: "2Na",
    level: 8,
    className: "Mercenary",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@halon_1211",
  },
  {
    id: 19,
    name: "Blood E",
    level: 18,
    className: "Vampire Ninja",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@BigDaddyErac",
  },
  {
    id: 20,
    name: "Yoss0x",
    level: 12,
    className: "Phunk Knight",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Yoss0x2",
  },
  {
    id: 21,
    name: "Sizzler",
    level: 12,
    className: "Comrade Knight",
    faction: "Pork",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Sizzler187",
  },
  {
    id: 22,
    name: "MCO Wolf",
    level: 23,
    className: "Bloodmoon Reaver",
    faction: "Pond",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@MCOWOLF101",
  },
  {
    id: 23,
    name: "IfiHad",
    level: 10,
    className: "Mystic Troubadour",
    faction: "Pond",
    location: "Empathic Forgotten Quarry",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@DuncanDunkk",
  },
  {
    id: 24,
    name: "Aft3rparty",
    level: 10,
    className: "Mfpurr Knight",
    faction: "Demplar",
    location: "Thieves Den Main Rooms",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@aft3rpartyeth_",
  },
  {
    id: 25,
    name: "ThisNthat",
    level: 13,
    className: "Negotiator",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@this_n_that0x",
  },
  {
    id: 26,
    name: "Nexus",
    level: 13,
    className: "Tank",
    faction: "Demplar",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@nexuscsail",
  },
  {
    id: 27,
    name: "Vucci",
    level: 10,
    className: "Water Mage",
    faction: "Demplar",
    location: "Tavern",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Vucc1_VMG",
  },
  {
    id: 28,
    name: "Toss & Boerboel",
    level: 10,
    className: "Tank",
    faction: "Pond",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 29,
    name: "ArtOfKula",
    level: 11,
    className: "Disco Mage",
    faction: "Pork",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@theartofkula",
  },
  {
    id: 30,
    name: "Pylons",
    level: 20,
    className: "Phunk Knight",
    faction: "Pond",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@PylonsXPP",
  },
  {
    id: 31,
    name: "Dustin",
    level: 15,
    className: "Luminara",
    faction: "Pond",
    location: "Meltdown Island",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@ThatDustinShow",
  },
  {
    id: 32,
    name: "Cary",
    level: 20,
    className: "Phunk Knight",
    faction: "Pond",
    location: "Great Stone Quarry",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Cary0x2",
  },
  {
    id: 33,
    name: "Lasagna Techno Pirate",
    level: 25,
    className: "Rogue",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@nf_talk",
  },
  {
    id: 34,
    name: "WhiteCrypto",
    level: 5,
    className: "Ninja",
    faction: "Demplar",
    location: "Watchtower",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 35,
    name: "Sparrow",
    level: 41,
    className: "Solo Warden",
    faction: "Pond",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "Training +5%, +5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Sparrow_X_",
  },
  {
    id: 36,
    name: "Rangiku",
    level: 40,
    className: "Blade Healer",
    faction: "Demplar",
    location: "Luminous",
    profileUrl:
      "https://images.ctfassets.net/b474hutgbdbv/3AYkauQlVdSQfVvdWtmaT/895be1409a709d60553bb820c213d45f/Rangiku.jpg",
    buffs:
      "Training +5%, +5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@rangichan",
  },
  {
    id: 37,
    name: "4Eyes",
    level: 12,
    className: "Light Mage",
    faction: "Pork",
    location: "Impala Mountains",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 38,
    name: "Mr Helm",
    level: 30,
    className: "Tank",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Mrhelm4",
  },
  {
    id: 39,
    name: "DizzyD",
    level: 30,
    className: "Time Mage",
    faction: "Pond",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@dizyd_eth",
  },
  {
    id: 40,
    name: "Megatron Chicken",
    level: 32,
    className: "Magic Chicken",
    faction: "Pork",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@ChickenLuver777",
  },
  {
    id: 41,
    name: "Naitsirk Comrade Phunk",
    level: 15,
    className: "Healer",
    faction: "Pond",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@naitsirk710",
  },
  {
    id: 42,
    name: "Victor Smash",
    level: 25,
    className: "Brawler",
    faction: "Pond",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Victor_Crypto07",
  },
  {
    id: 43,
    name: "Jayfeezy",
    level: 24,
    className: "Arcane Mage",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@JayFeezy",
  },
  {
    id: 44,
    name: "Von The Techsavvy",
    level: 37,
    className: "Time Traveler",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@vonZZZZZZZZZ",
  },
  {
    id: 45,
    name: "yuTj telluhwat Knight",
    level: 11,
    className: "Adventurer",
    faction: "Pork",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@I_lov_tj",
  },
  {
    id: 46,
    name: "Will Billy The Hill Billy",
    level: 23,
    className: "Stormcloak Farmer",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@willparkskc8puw",
  },
  {
    id: 47,
    name: "Fork Knight",
    level: 52,
    className: "Time Traveler",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@N___d____Y__",
  },
  {
    id: 48,
    name: "Ranger The Potato Knight",
    level: 15,
    className: "Tank",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@TheePotato_King",
  },
  {
    id: 49,
    name: "Kold Dragon",
    level: 32,
    className: "Dragon Knight",
    faction: "Demplar",
    location: "Luminous",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@OGkolddragon",
  },
  {
    id: 50,
    name: "Raptor",
    level: 12,
    className: "Mythical Beast",
    faction: "Demplar",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@TheRaptorRoost",
  },
  {
    id: 51,
    name: "Sumdog",
    level: 8,
    className: "Knight",
    faction: "Pork",
    location: "Badlands",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Sumdog9879",
  },
  {
    id: 52,
    name: "Paul The Blacksmith",
    level: 23,
    className: "Blacksmith",
    faction: "Pork",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 53,
    name: "AGZ Mage Thief",
    level: 13,
    className: "Portal User",
    faction: "Demplar",
    location: "Sewer 8",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 54,
    name: "Pauly",
    level: 10,
    className: "Mysterious",
    faction: "Pond",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 55,
    name: "Classmomma",
    level: 5,
    className: "OG Miner",
    faction: "Pond",
    location: "Great Stone Quarry",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@classmomma1206",
  },
  {
    id: 56,
    name: "Magpie",
    level: 16,
    className: "Light Mage",
    faction: "Demplar",
    location: "Tavern",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@MagpieMeme",
  },
  {
    id: 57,
    name: "WTF InATruck",
    level: 18,
    className: "Knight",
    faction: "Pond",
    location: "Empathic Forgotten Water",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@wtfinatruck",
  },
  {
    id: 58,
    name: "UnknownAssassin",
    level: 15,
    className: "Ninja",
    faction: "Pork",
    location: "Thieves Den",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@unknownlee515",
  },
  {
    id: 59,
    name: "Mitchell The Brave",
    level: 27,
    className: "Sea Soned Adventurer",
    faction: "Pond",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@MitchellC420",
  },
  {
    id: 60,
    name: "Matt Furie",
    level: 1,
    className: "Illustrator",
    faction: "Pond",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Matt_Furie",
  },
  {
    id: 61,
    name: "Younghover",
    level: 14,
    className: "Emoji Ninja",
    faction: "Demplar",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@younghover1996",
  },
  {
    id: 63,
    name: "Jay Vampiric",
    level: 14,
    className: "Vampire Ninja",
    faction: "Pond",
    location: "Badlands",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 64,
    name: "BrewLee",
    level: 25,
    className: "Martial Artist",
    faction: "Pork",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@TapuBulu0x",
  },
  {
    id: 65,
    name: "Sir Quiet",
    level: 17,
    className: "Undead Phunk Knight",
    faction: "Pond",
    location: "Impala Mountains",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@srquiet0x",
  },
  {
    id: 66,
    name: "Unempyd",
    level: 18,
    className: "Knight Captain",
    faction: "Pond",
    location: "Kingdom",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@unempyd",
  },
  {
    id: 67,
    name: "IamDon",
    level: 1,
    className: "Support",
    faction: "Pond",
    location: "Impala Mountains",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@iAmDon_eth",
  },
  {
    id: 68,
    name: "Outsider",
    level: 7,
    className: "Spirit Dragoon Phunk",
    faction: "Demplar",
    location: "Badlands",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 69,
    name: "Unknown [NPC]",
    level: 800,
    className: "Demplar",
    faction: "NPC",
    location: "Compression of Time",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 70,
    name: "MJDesigns",
    level: 4,
    className: "Druid",
    faction: "Demplar",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 71,
    name: "Daniel0x",
    level: 32,
    className: "Reaper",
    faction: "Pond",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Deag7",
  },
  {
    id: 72,
    name: "Jlee",
    level: 12,
    className: "Viking Bard",
    faction: "Pork",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@JLEEWALLS1",
  },
  {
    id: 73,
    name: "RhiannonNFT",
    level: 2,
    className: "Knight",
    faction: "Pork",
    location: "Library",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@RhiannonNft",
  },
  {
    id: 74,
    name: "DonDennis",
    level: 7,
    className: "Demplar",
    faction: "Pond",
    location: "Tavern",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@MadProducers",
  },
  {
    id: 75,
    name: "Sativa",
    level: 7,
    className: "Healer",
    faction: "Demplar",
    location: "Enchanted Forest",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "",
  },
  {
    id: 76,
    name: "Breathe",
    level: 29,
    className: "Water Mage",
    faction: "Pond",
    location: "Dark Cave of Unknown",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@SNftbreathe",
  },
  {
    id: 77,
    name: "Atlantis",
    level: 1,
    className: "Demplar",
    faction: "Demplar",
    location: "Tavern",
    profileUrl: "",
    buffs:
      "Training +5%, Crafting +5%, +5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@Altcoin_Q",
  },
  {
    id: 78,
    name: "Captain Cohiba",
    level: 17,
    className: "Knight Captain",
    faction: "Pond",
    location: "Wayameru",
    profileUrl: "",
    buffs:
      "+5% attack, +5% defense, +5% agility, +5% critical, +5% luck, +5% magic defense",
    twitterHandle: "@RedHornMagnm",
  },
];
